### ISSUE TITLE
Failure to comunicate with website

### ISSUE THREAD

**Issue by georgemaxim** [Aksimant/storjboard#5]
Im on Ubuntu 16 and I get this error in the logs.

```
==> /home/george/.pm2/logs/storjbaord-error-0.log <==
Error: Cannot find module 'dnode'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Timeout.requestInfo [as _onTimeout] (/home/george/storjboard-0.0.16/script_storjboard.js:3:19)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

==> /home/george/.pm2/logs/storjbaord-out-0.log <==
Start first update in 5 min
```

Please help

**Comment by baskinsy** [comment]
try

``npm install dnode`` 

and probably you will need also

``npm install request``
